import { AIRequest, ProviderResponse } from '../types/ai.types';
import { AIProvider } from './AIProvider';

/**
 * OpenAIProvider
 * Mock provider simulating OpenAI gpt models responses.
 */
export class OpenAIProvider extends AIProvider {
  public readonly name = 'OPENAI';

  public async generateText(request: AIRequest, _requestId: string): Promise<ProviderResponse> {
    const model = request.modelOverride || 'gpt-4o';

    // Simulate minor network delay
    await new Promise((resolve) => setTimeout(resolve, 300));

    // Simple word count mock for tokens
    const promptText = (request.template.systemPrompt + request.template.userPrompt).substring(
      0,
      300
    );
    const mockText = `[Mock OpenAI Response]\n\nBased on your profile, here is a draft generated by model "${model}" utilizing your target studies. User variables: ${JSON.stringify(request.variables)}`;

    const promptTokens = Math.round(promptText.length / 4) + 10;
    const completionTokens = Math.round(mockText.length / 4) + 10;

    return {
      text: mockText,
      model,
      usage: {
        promptTokens,
        completionTokens,
        totalTokens: promptTokens + completionTokens,
      },
      finishReason: 'stop',
    };
  }
}
export default OpenAIProvider;
