import React, { useState, useEffect } from 'react';
import { documentService } from '@/features/documents/services/document.service';

interface ActivityTimelineProps {
  documentId: string;
}

interface ActivityItem {
  id: string;
  activityType:
    'CREATED' | 'GENERATED' | 'EDITED' | 'REGENERATED' | 'RESTORED' | 'FINALIZED' | 'ARCHIVED';
  metadata: unknown;
  createdAt: string;
}

export const ActivityTimeline: React.FC<ActivityTimelineProps> = ({ documentId }) => {
  const [activities, setActivities] = useState<ActivityItem[]>([]);
  const [page, setPage] = useState(1);
  const [hasMore, setHasMore] = useState(true);
  const [loading, setLoading] = useState(false);

  const fetchActivities = React.useCallback(
    async (pageNum: number) => {
      setLoading(true);
      try {
        const response = await documentService.getActivities(documentId, pageNum, 5);
        const newItems = (response.data || []) as ActivityItem[];

        setActivities((prev) => {
          if (pageNum === 1) return newItems;
          const merged = [...prev];
          newItems.forEach((item) => {
            if (!merged.some((m) => m.id === item.id)) {
              merged.push(item);
            }
          });
          return merged;
        });

        setHasMore(response.metadata.total > pageNum * 5);
        setPage(pageNum);
      } catch (err) {
        console.error('Failed to retrieve timeline logs:', err);
      } finally {
        setLoading(false);
      }
    },
    [documentId]
  );

  useEffect(() => {
    setActivities([]);
    fetchActivities(1);
  }, [documentId, fetchActivities]);

  const getActivityStyles = (type: string) => {
    switch (type) {
      case 'CREATED':
        return { icon: '★', bg: 'bg-slate-800 border-slate-700 text-slate-300' };
      case 'GENERATED':
        return { icon: '⚡', bg: 'bg-brand-500/20 border-brand-500/35 text-brand-400' };
      case 'EDITED':
        return { icon: '✎', bg: 'bg-amber-500/10 border-amber-500/20 text-amber-400' };
      case 'REGENERATED':
        return { icon: '⟳', bg: 'bg-purple-500/20 border-purple-500/30 text-purple-400' };
      case 'RESTORED':
        return { icon: '⎋', bg: 'bg-cyan-500/10 border-cyan-500/20 text-cyan-400' };
      case 'FINALIZED':
        return { icon: '✓', bg: 'bg-emerald-500/20 border-emerald-500/30 text-emerald-400' };
      case 'ARCHIVED':
        return { icon: '☒', bg: 'bg-red-500/10 border-red-500/20 text-red-400' };
      default:
        return { icon: '•', bg: 'bg-slate-900 border-slate-800 text-slate-400' };
    }
  };

  return (
    <div className="space-y-6 select-none font-sans">
      {activities.length === 0 && !loading && (
        <div className="py-6 text-center text-xs text-slate-600 italic">No logs recorded.</div>
      )}

      {/* Vertical timeline timeline items */}
      <div className="relative pl-6 space-y-6 before:absolute before:left-2.5 before:top-2 before:bottom-2 before:w-[1px] before:bg-slate-900">
        {activities.map((act) => {
          const style = getActivityStyles(act.activityType);
          const dateStr = new Date(act.createdAt).toLocaleDateString('en-US', {
            month: 'short',
            day: 'numeric',
            hour: '2-digit',
            minute: '2-digit',
          });

          return (
            <div key={act.id} className="relative flex gap-3 items-start text-xs animate-fade-in">
              {/* Circle dot icon */}
              <div
                className={[
                  'absolute -left-6 w-5 h-5 rounded-full flex items-center justify-center border text-[9px] font-bold shrink-0',
                  style.bg,
                ].join(' ')}
              >
                {style.icon}
              </div>

              <div>
                <p className="font-semibold text-slate-200">
                  {act.activityType === 'CREATED' && 'Document record created'}
                  {act.activityType === 'GENERATED' && 'SOP Draft generated by AI'}
                  {act.activityType === 'EDITED' && 'Manual rich edits saved'}
                  {act.activityType === 'REGENERATED' && 'AI SOP regeneration applied'}
                  {act.activityType === 'RESTORED' &&
                    `Restored to version v${(act.metadata as { versionRestored?: number })?.versionRestored || ''}`}
                  {act.activityType === 'FINALIZED' && 'Document finalized'}
                  {act.activityType === 'ARCHIVED' && 'Document archived'}
                </p>
                <span className="text-[10px] text-slate-500 block mt-0.5">{dateStr}</span>
              </div>
            </div>
          );
        })}
      </div>

      {hasMore && (
        <div className="pt-2 flex justify-center">
          <button
            type="button"
            onClick={() => fetchActivities(page + 1)}
            disabled={loading}
            className="px-4 h-8 bg-slate-900 border border-slate-800 text-slate-400 hover:text-white rounded-xl text-xs font-semibold disabled:opacity-50 transition-all"
          >
            {loading ? 'Loading...' : 'Load more activities'}
          </button>
        </div>
      )}
    </div>
  );
};

export default ActivityTimeline;
